// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230912122250_id")]
    partial class id
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Models.TaskListName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedTasks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingTasks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaskListNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedTasks = 2,
                            Name = "Work",
                            PendingTasks = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletedTasks = 1,
                            Name = "Personal",
                            PendingTasks = 1
                        });
                });

            modelBuilder.Entity("TaskManager.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskListNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskListNameId");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = true,
                            Name = "Finish project A",
                            TaskListNameId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Name = "Meeting with client",
                            TaskListNameId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Name = "Grocery shopping",
                            TaskListNameId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = true,
                            Name = "Write report",
                            TaskListNameId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = true,
                            Name = "Exercise",
                            TaskListNameId = 2
                        });
                });

            modelBuilder.Entity("TaskManager.Models.UserTask", b =>
                {
                    b.HasOne("TaskManager.Models.TaskListName", "TaskListName")
                        .WithMany("UserTasks")
                        .HasForeignKey("TaskListNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskListName");
                });

            modelBuilder.Entity("TaskManager.Models.TaskListName", b =>
                {
                    b.Navigation("UserTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
